WebApplication1/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Message
    {
        public int A_Id { get; set; }
        public int M_Id { get; set; }

        [DisplayName("留言帳號:")]
        public string Account { get; set; }

        [DisplayName("留言內容:")]
        public string Content { get; set; }

        [DisplayName("留言時間:")]
        public DateTime CreateTime { get; set; }
        public Members Member { get; set; } = new Members();
    }
}

WebApplication1/ViewModels/MessageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication1.Models;
using WebApplication1.Serivces;

namespace WebApplication1.ViewModels
{
    public class MessageViewModel
    {
        public List<Message> DataList { get; set; }

        public ForPaging Paging { get; set; }

        public int A_Id { get; set; }
    }
}

WebApplication1/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Serivces;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class MessageController : Controller
    {
        private readonly MessageDBService messageService = new MessageDBService();
        // GET: Message

        #region 留言頁面
        public ActionResult Index(int A_Id = 1)
        {
            ViewData["A_Id"] = A_Id;
            return PartialView();
        }
        #endregion

        #region 留言陣列
        public ActionResult MessageList(int A_Id, int Page = 1)
        {
            MessageViewModel Data = new MessageViewModel();
            Data.Paging = new ForPaging(Page);
            Data.A_Id = A_Id;
            Data.DataList = messageService.GetDataList(Data.Paging, Data.A_Id);
            return PartialView(Data);
        }
        #endregion

        #region 新增留言
        [Authorize]
        public ActionResult Create(int A_Id)
        {
            ViewData["A_Id"] = A_Id;
            return PartialView();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Add(int A_Id, [Bind(Include = "Content")]Message Data)
        {
            Data.A_Id = A_Id;
            Data.Account = User.Identity.Name;
            messageService.InsertMessage(Data);
            return RedirectToAction("MessageList", new { A_Id = Data.A_Id });
        }
        #endregion

        #region 修改留言
        [Authorize]
        public ActionResult UpdateMessage(int A_Id,int M_Id,string Content)
        {
            Message message = new Message();
            message.A_Id = A_Id;
            message.M_Id = M_Id;
            message.Content = Content;
            messageService.UpdateMessage(message);
            return RedirectToAction("Article", "Article", new { A_Id = A_Id });
        }
        #endregion

        #region 刪除留言
        [Authorize]
        public ActionResult DeleteMessage(int A_Id, int M_Id)
        {
            messageService.DeleteMessage(A_Id, M_Id);
            return RedirectToAction("Article", "Article", new { A_Id = A_Id });
        } 
        #endregion
    }
}

WebApplication1/Views/Message/Create.cshtml
@model WebApplication1.Models.Message

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Ajax.BeginForm("Add","Message",new { A_Id = ViewData["A_Id"]},new AjaxOptions { InsertionMode = InsertionMode.Replace,UpdateTargetId="MessageList"}))
{
   <table>
       <tr>
           <td>
               @Html.TextBoxFor(model => model.Content, new { @class = "form-control"})
               @Html.ValidationMessageFor(model => model.Content)
           </td>
           <td>
               <input id="createMessage" class="btn btn-primary" type="submit" value="留言"/>
           </td>
       </tr>
   </table>
}

WebApplication1/Views/Message/Index.cshtml
<div id="DataList">
    @Html.Action("MessageList",new{ A_Id = ViewData["A_Id"]})
</div>
<div id="MessageCreate">
    @if (User.Identity.IsAuthenticated)
    {
        @Html.Action("Create",new{ A_Id = ViewData["A_Id"]})
    }
    else
    {
        <text>要留言請先</text>
        @Html.ActionLink("登入","Login","Members")
    }
</div>

WebApplication1/Views/Message/MessageList.cshtml
@model WebApplication1.ViewModels.MessageViewModel

@{
    ViewBag.Title = "MessageList";
}

<div id="MessageList">
    <h2>留言區</h2>
    <table>
        @if (!Model.DataList.Count.Equals(0))
        {
            foreach (var item in Model.DataList)
            {
                <tr>
                    <td>
                        @Html.LabelFor(model => model.DataList[0].Account)
                    </td>
                    <td>
                        @item.Account
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.DataList[0].Content)
                    </td>
                    <td colspan="3">
                        @item.Content
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.DataList[0].CreateTime)
                    </td>
                    <td>
                        @item.CreateTime
                    </td>
                </tr>
                if (User.Identity.IsAuthenticated)
                {
                    if (User.Identity.Name == item.Account)
                    {
                        <tr>
                            <td id="EditMessageBlock" colspan="2">
                                <button class="editMessage btn btn-primary">修改留言</button>
                                <button class="btn btn-danger" onclick="location.href = '@Url.Action("DeleteMessage","Message"
                                 ,new { M_Id = item.M_Id, A_Id = item.A_Id})';return false;">
                                    刪除留言
                                </button>
                            </td>
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td colspan="2">
                                非此則留言者不可進行修改、刪除等動作
                            </td>
                        </tr>
                    }
                }
            }
        }
        else
        {
            <tr>
                <td colspan="4">
                    本篇文章尚未有人留言
                </td>
            </tr>
        }
    </table>
    <div class="col-xs-12 text-center">
        <ul class="pagination">
            <li class="@((Model.Paging.NowPage>1) ? "":"disabled")">
                @Ajax.ActionLink("<<", "MessageList", new { A_Id = Model.A_Id, Page = 1 },
                    new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "DataList" })
            </li>
            <li class="@((Model.Paging.NowPage>1)?"":"disabled")">
                @Ajax.ActionLink("<", "MessageList", new { A_Id = Model.A_Id, Page = Model.Paging.NowPage - 1 },
                    new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "DataList" })
            </li>
            @for (var page = (Model.Paging.NowPage - 5); page < (Model.Paging.NowPage + 5); page++)
            {
                if ((page > 0) && page <= Model.Paging.MaxPage)
                {
                    if (page == Model.Paging.NowPage)
                    {
                        <li class="active">
                            <a href="#">@page</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            @Ajax.ActionLink(page.ToString(), "MessageList", new { A_Id = Model.A_Id, Page = page }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "DataList" })
                        </li>
                    }
                }
            }
            <li class="@((Model.Paging.NowPage<Model.Paging.MaxPage) ? "":"disabled")">
                @Ajax.ActionLink(">", "MessageList", new { A_Id = Model.A_Id, Page = Model.Paging.NowPage + 1 },
                    new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "DataList" })
            </li>
            <li class="@((Model.Paging.NowPage<Model.Paging.MaxPage)?"":"disabled")">
                @Ajax.ActionLink(">>", "MessageList", new { A_Id = Model.A_Id, Page = Model.Paging.MaxPage },
                    new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "DataList" })
            </li>
        </ul>
    </div>
</div>