WebApplication1/Models/Guestbooks.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Guestbooks
    {
        [DisplayName("編號：")]
        public int Id { get; set; }

        public string Account { get; set; }

        [DisplayName("留言內容：")]
        [Required(ErrorMessage = "請輸入留言內容")]
        [StringLength(100, ErrorMessage = "留言內容不可超過100字元")]
        public string Content { get; set; }

        [DisplayName("新增時間：")]
        public DateTime CreateTime { get; set; }

        [DisplayName("回覆內容：")]
        [StringLength(100, ErrorMessage = "回覆內容不可超過100字元")]
        public string Reply { get; set; }

        [DisplayName("回覆時間：")]
        public DateTime? ReplyTime { get; set; }

        public Members Member { get; set; } = new Members();
    }
}

WebApplication1/ViewModels/GuestbooksViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using WebApplication1.Models;
using WebApplication1.Serivces;

namespace WebApplication1.ViewModels
{
    public class GuestbooksViewModel
    {
        [DisplayName("搜尋：")]
        public string Search { get; set; }
        public List<Guestbooks> DataList { get; set; }
        public ForPaging Paging { get; set; }
    }
}

WebApplication1/Controllers/GuestbooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Serivces;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class GuestbooksController : Controller
    {
        private readonly GuestbooksDBService GuestbookService = new GuestbooksDBService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetDataList(string Search, int Page = 1)
        {
            GuestbooksViewModel Data = new GuestbooksViewModel();
            Data.Search = Search;
            Data.Paging = new ForPaging(Page);
            Data.DataList = GuestbookService.GetDataList(Data.Paging, Data.Search);
            return PartialView(Data);
        }
        [HttpPost]
        public ActionResult GetDataList([Bind(Include ="Search")] GuestbooksViewModel Data)
        {
            return RedirectToAction("GetDataList", new { Search = Data.Search });
        }

        #region 新增留言
        public ActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        [Authorize]
        public ActionResult Create([Bind(Include = "Content")]Guestbooks Data)
        {
            Data.Account = User.Identity.Name;
            GuestbookService.InsertGuestbooks(Data);
            return RedirectToAction("Index");
        }
        #endregion

        #region 修改留言
        public ActionResult Edit(int Id)
        {
            Guestbooks Data = GuestbookService.GetDataById(Id);
            return View(Data);
        }
        [HttpPost]
        [Authorize]
        public ActionResult Edit(int Id, [Bind(Include = "Content")]Guestbooks UpdateData)
        {
            if (GuestbookService.CheckUpdate(Id))
            {
                UpdateData.Id = Id;
                UpdateData.Account = User.Identity.Name;
                GuestbookService.UpdateGuestbooks(UpdateData);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region 回覆留言
        public ActionResult Reply(int Id)
        {
            Guestbooks Data = GuestbookService.GetDataById(Id);
            return View(Data);
        }

        [HttpPost]
        [Authorize(Roles ="Admin")]
        public ActionResult Reply(int Id, [Bind(Include = "Reply,ReplyTime")]Guestbooks ReplyData)
        {
            if (GuestbookService.CheckUpdate(Id))
            {
                ReplyData.Id = Id;
                GuestbookService.ReplyGuestbooks(ReplyData);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region 刪除留言
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int Id)
        {
            GuestbookService.DeleteGuestbooks(Id);
            return RedirectToAction("Index");
        }
        #endregion

    }
}

WebApplication1/Views/Guestbooks/Create.cshtml
@model WebApplication1.Models.Guestbooks


@using (Html.BeginForm("Create", "Guestbooks"))
{
    <h3>新增留言</h3>
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
    </table>
    <input type="submit" value="新增留言" />
}

WebApplication1/Views/Guestbooks/Edit.cshtml
@model WebApplication1.Models.Guestbooks

@{
    ViewBag.Title = "修改留言";
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval.js")
}
@using (Html.BeginForm())
{
    <h3>修改留言</h3>

    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
    </table>
    if (Model.ReplyTime == null)
    {
        <input type="submit" value="修改留言" />
    }
    else
    {
        <text>此留言已回覆無法修改，請</text>
        @Html.ActionLink("返回列表", "Index")
    }
}

WebApplication1/Views/Guestbooks/GetDataList.cshtml
@model WebApplication1.ViewModels.GuestbooksViewModel

@{
    ViewBag.Title = "GetDataList";
}

<div id="DataList">
    <h2>留言板</h2>
    @using (Ajax.BeginForm("Index", "Guestbooks", new AjaxOptions { InsertionMode=InsertionMode.Replace,UpdateTargetId="DataList"}))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Search)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Search)
                </td>
                <td>
                    <input type="submit" value="搜尋" />
                </td>
            </tr>
        </table>
    }
    <table>
        @if (!Model.DataList.Count.Equals(0))
        {
            foreach (var item in Model.DataList)
            {
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Member.Name)
                    </td>
                    <td>
                        @item.Member.Name
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].CreateTime)
                    </td>
                    <td>
                        @item.CreateTime
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Content)
                    </td>
                    <td colspan="3">
                        @item.Content
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Reply)
                    </td>
                    <td colspan="3">
                        @item.Reply
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].ReplyTime)
                    </td>
                    <td>
                        @item.ReplyTime
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        @Html.ActionLink("修改留言", "Edit", new { Id = item.Id })
                        @if (User.IsInRole("Admin"))
                        {
                            @Html.ActionLink("回覆留言", "Reply", new { Id = item.Id })
                            @Html.ActionLink("刪除留言", "Delete", new { Id = item.Id })
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="4">
                    資料庫內查無資料
                </td>
            </tr>
        }
        <tr>
            <td>
                @if (Model.Paging.NowPage > 1)
                {
                    @Ajax.ActionLink("<<", "GetDataList", new { Page = 1, Search = Model.Search }, new AjaxOptions { InsertionMode=InsertionMode.Replace,UpdateTargetId="DataList"})
                    @Ajax.ActionLink("<", "GetDataList", new { Page = Model.Paging.NowPage - 1, Search = Model.Search }, new AjaxOptions { InsertionMode=InsertionMode.Replace,UpdateTargetId="DataList"})
                }
            </td>
            <td>
                @for (var page = (Model.Paging.NowPage - 6); page < (Model.Paging.NowPage +
                    6); page++)
                {
                    if ((page > 0) && (page <= Model.Paging.MaxPage))
                    {
                        if (page == Model.Paging.NowPage)
                        {
                            <b>@page</b>
                        }
                        else
                        {
                            @Ajax.ActionLink(page.ToString(), "GetDataList", new { Page = page, Search = Model.Search }, new AjaxOptions { InsertionMode=InsertionMode.Replace,UpdateTargetId="DataList"})
                        }
                    }
                }
            </td>
            <td>
                @if (Model.Paging.NowPage < Model.Paging.MaxPage)
                {
                    @Ajax.ActionLink(">", "GetDataList", new { Page = Model.Paging.NowPage + 1, Search = Model.Search }, new AjaxOptions { InsertionMode=InsertionMode.Replace,UpdateTargetId="DataList"})
                    @Ajax.ActionLink(">>", "GetDataList", new { Page = Model.Paging.MaxPage, Search = Model.Search }, new AjaxOptions { InsertionMode=InsertionMode.Replace,UpdateTargetId="DataList"})
                }
            </td>
        </tr>

    </table>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Guestbooks/Index.cshtml
@model WebApplication1.ViewModels.GuestbooksViewModel

@{
    ViewBag.Title = "Index";
}

@Html.AntiForgeryToken()

<div id="CreateData">
    @Html.Action("Create")
</div>

@Html.Action("GetDataList") 


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Guestbooks/Reply.cshtml
@model WebApplication1.Models.Guestbooks
@{
    ViewBag.Title = "回覆留言";
}
@using (Html.BeginForm())
{
    <h3>回覆留言</h3>
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Reply)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Reply)
                @Html.ValidationMessageFor(model => model.Reply)
            </td>
        </tr>
    </table>
    if (Model.ReplyTime == null)
    {
        <input type="submit" value="回覆留言" />
    }
    else
    {
        <text>此留言已回覆，請</text>
        @Html.ActionLink("返回列表", "Index")
    }
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval.js")
}